name: Mammouth API
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CARNET_API_KEY: ${{ secrets.CARNET_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: node api/parse-meal.js
